# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "trusty64server"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.ssh.username = 'vagrant'
  config.ssh.forward_agent = true

  config.vm.define :dataservices do |dataservices|
    dataservices.vm.network :public_network, :bridge => 'eth0', :auto_config => false
    # Using private network fixes the thumbnail issue
    # Ref: https://github.com/Kitware/minerva/pull/98#issuecomment-139023062
    config.vm.network "private_network", ip: "192.168.33.12"
    dataservices.vm.provider :virtualbox do |vb|
       vb.customize [ "modifyvm", :id, "--name", "minerva-dataservices","--memory", 4096 ]
  	end
    dataservices.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = "vvvv"
        ansible.host_key_checking = false
    end
  end
end
